core/urls.py
from django.urls import path,include
from . import views
from core.views import FeedbackFormView, SuccessView

app_name = 'core'

urlpatterns = [
    path('', views.total, name="core"),
    path("feedback/", FeedbackFormView.as_view(), name="feedback"),
    path("success/", SuccessView.as_view(), name="success"),
]

docker_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

from core.tasks import send_feedback_email_task


class FeedbackForm(forms.Form):
    email = forms.EmailField(label="Email Address")
    message = forms.CharField(
        label="Message", widget=forms.Textarea(attrs={"rows": 5})
    )

    def send_email(self):
        send_feedback_email_task.delay(
            self.cleaned_data["email"], self.cleaned_data["message"]
        )

core/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from .tasks import *

from core.forms import FeedbackForm



def total(request):
    res = add.delay(4, 5)
    return HttpResponse(res)


class FeedbackFormView(FormView):
    template_name = "core/feedback.html"
    form_class = FeedbackForm
    success_url = "/success/"

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class SuccessView(TemplateView):
    template_name = "core/success.html"

core/templates/core/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/bamboo.css">
    <title>Feedback</title>
</head>
<body>

    {% block content %}

    {% endblock content %}

</body>
</html>

core/templates/core/feedback.html
{% extends 'core/base.html' %}

{% block content %}

    <h1>How are we doing?</h1>
    
    <p>Please send us your feedback.</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"/>
    </form>

{% endblock content %}

core/templates/core/success.html
{% extends 'core/base.html' %}

{% block content %}

<h1>Thank You!</h1>

<p>Your feedback has been recorded.</p>
<p>If you have more to say, you can <a href="{% url 'core:feedback' %}">submit another feedback</a> response.</p>

{% endblock content %}